### ISSUE TITLE
So many errors in net-driver, when it works on php 7.2 

### ISSUE THREAD

**Issue by sakurashiki** [stk2k/phitflyer#5]
There are too many errors that I can't resolve them, when `meCancelAllChildOrders` works on php 7.2.

**Comment by stk2k** [comment]
what is this issue for? for phitflyer?
you should write error examples when you report issues so that i can judge how i should do on this library.
(unfortunately i have no time to fix and test this library...)

if you have errors in net-driver, you can write pull request in net-driver project.
you should not write issues of different library.

if you have errors in phitflyer library, you can write pull request here.
i will do nothing when you just write "many errors", because i have no time to investigate bugs any more.
